// <auto-generated />
using Aplikasi_Pengajuan_Cuti.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplikasi_Pengajuan_Cuti.Migrations
{
    [DbContext(typeof(myContext))]
    partial class myContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Cuti", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alasan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_pegawai")
                        .HasColumnType("int");

                    b.Property<int>("id_status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_pegawai");

                    b.HasIndex("id_status");

                    b.ToTable("cuti");
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Division", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nama_division")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("division");
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Pegawai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_division")
                        .HasColumnType("int");

                    b.Property<string>("nama_pegawai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_division");

                    b.ToTable("pegawai");
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name_role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("status_cuti")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("status");
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Userr", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("id_role")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.HasIndex("id_role");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Cuti", b =>
                {
                    b.HasOne("Aplikasi_Pengajuan_Cuti.Models.Pegawai", "Pegawai")
                        .WithMany()
                        .HasForeignKey("id_pegawai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplikasi_Pengajuan_Cuti.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("id_status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Pegawai", b =>
                {
                    b.HasOne("Aplikasi_Pengajuan_Cuti.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("id_division")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplikasi_Pengajuan_Cuti.Models.Userr", b =>
                {
                    b.HasOne("Aplikasi_Pengajuan_Cuti.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
